### PR TITLE
44 menu for rooms

### LINKED ISSUE #44: Neue Räume hinzufügen
Als Planer möchte ich,
neue Räume zu den Eingangsdaten hinzufügen können,
z.B. wenn mir seitens der Universität ein ganz unbekannter Raum (z.B. im Zweitzugriffsrecht) freigegeben wird.

### PR DESCRIPTION
**Pull request by roschaefer**
resolves #44 

@felixKubicek review plz

### CODE REVIEW

**Comment by felixKubicek** [comment]
do we need the json stuff?

**Comment by felixKubicek** [comment]
anyway! merged!

**Comment by roschaefer** [comment]
In this moment I was looking up the ```format as json```documentation of rails.. I wasn't sure either If we actually need it.

**Comment by felixKubicek** [comment]
Guess it would only make sense if we would have ajax requests. Think we neither need neitherformat.html, nor format.json.

**Pull request merged**
